# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c101ca3f177225be642056b9641997cf45923f291f379df40aa775798b1339f0a5dd1dd3ece27eb710762aded1867285578cac41c34bc5277db3eba2f9b1947a

test:
  secret_key_base: 7f4e3da5dffc6e7b44f3a8c4835a0aa7992c6c10693ab1acc929e12ff6c2ebd7b00d657596731aafbae501f53a52788ff1f4e5249a902bcc679d4a16c4840082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
